"""Add detailed fields to artist_payouts

Revision ID: 033bc339a6a7
Revises: a4154a0f59c3
Create Date: 2026-02-25 18:28:36.022613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033bc339a6a7'
down_revision = 'a4154a0f59c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_payouts', schema=None) as batch_op:
        # First, handle the existing 'amount' column data if needed
        # Add new columns (make them nullable initially for existing records)
        batch_op.add_column(sa.Column('gross_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True, server_default='0.20'))
        batch_op.add_column(sa.Column('commission_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payout_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True, server_default='mpesa'))
        batch_op.add_column(sa.Column('payment_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('painting_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        
        # Add foreign keys with explicit names
        batch_op.create_foreign_key('fk_artist_payouts_order_id', 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key('fk_artist_payouts_painting_id', 'paintings', ['painting_id'], ['id'])
        
        # Drop the old amount column
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        
        # Drop foreign keys by name
        batch_op.drop_constraint('fk_artist_payouts_painting_id', type_='foreignkey')
        batch_op.drop_constraint('fk_artist_payouts_order_id', type_='foreignkey')
        
        batch_op.drop_column('processed_at')
        batch_op.drop_column('painting_id')
        batch_op.drop_column('order_id')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_phone')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payout_amount')
        batch_op.drop_column('commission_amount')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('gross_amount')

    # ### end Alembic commands ###