"""Add shipping fields to delivery

Revision ID: 400b49544319
Revises: 033bc339a6a7
Create Date: 2026-03-04 03:19:38.551510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400b49544319'
down_revision = '033bc339a6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_payouts', schema=None) as batch_op:
        batch_op.alter_column('gross_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('commission_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('payout_amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('carrier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('actual_delivery')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('carrier')
        batch_op.drop_column('tracking_number')

    with op.batch_alter_table('artist_payouts', schema=None) as batch_op:
        batch_op.alter_column('payout_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('commission_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('gross_amount',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
