"""Add location and materials to Painting model

Revision ID: 85c00d5d7caa
Revises: 9346d359a939
Create Date: 2026-01-22 21:41:47.985166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c00d5d7caa'
down_revision = '9346d359a939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('materials')

    # ### end Alembic commands ###
