"""Add IPFS CID and QR code URL to Painting model

Revision ID: 9346d359a939
Revises: ec7092f63a7e
Create Date: 2026-01-22 21:08:31.556394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9346d359a939'
down_revision = 'ec7092f63a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipfs_cid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qr_code_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_column('qr_code_url')
        batch_op.drop_column('ipfs_cid')

    # ### end Alembic commands ###
